### ISSUE TITLE
adjustment proposal for logotype

### ISSUE THREAD

**Issue by sableweasel** [bisq-network/bisq-design#3]
Hi, there. I might have an adjustment proposal for the mark (cat sign).
It’s a minor thing but I would be interested in opinions.

<img width="485" alt="adjustment_proposal" src="https://user-images.githubusercontent.com/45734965/50281154-da6c4680-044e-11e9-9ab9-e58f55a30748.png">

**Comment by sableweasel** [comment]
I did some more.

![bisq_logo_proposals@4x](https://user-images.githubusercontent.com/45734965/55102206-31c12900-50c6-11e9-91ba-4e93f276e714.png)

**Comment by ManfredKarrer** [comment]
Thanks for your suggestions but to be honest I am super happy with the current logo. The slightly too big ear makes it special IMO. If it is too symmetric it loses some attention.

**Comment by sableweasel** [comment]
I get what you mean.
